motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: '([AP].?M .+?)\n\n(.+?)\n\nWoordvoerder: (.+?)\n\nOnderwerp: (.+?)\n\nPreadvies: (.+?)\n\n(.+?)(?=[AP].?M|\Z)'
    groups:
        - id
        - ignore
        - author
        - title
        - decision
        - text
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - .+?, Delegierter?