motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: (\d+?)\t(.+?)\t(Categorie \d)(.+?)(?=\n\n\d+?\t|\Z)
    groups:
        - id
        - author
        - ignore
        - text
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - .+?, Delegierter?