motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: ([A-Z]\.)[\t\s](.+?)\n\n(.+?)— Ingediend door (.+?)\n\n(.+?)(?=\n\n[A-Z]\.\t|\Z)
    groups:
        - id
        - title
        - text
        - author
        - ignore
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - .+?, Delegierter?