motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: '(\d\d\.\d\d)\s(.+?)\n\nChair:\s?(.+?)\n\nAide:\s?(.+?)\n\nHall Aide:\s?(.+?)\n\n(.+?)\s(.+?)\n\n(.+?)(?=\d\d\.\d\d\sPolicy|\Z)'
    groups:
        - ignore
        - motion_type
        - chair
        - aide
        - hall_aide
        - id
        - title
        - text
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - .+?, Delegierter?