motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: ((Initiativ-)?Antrag Nr\. ([A-Z]?\d+)(\s-.+?)?)\n\n(.+?)\n\n(.+?)(?=\nInitiativ|\nAntrag|\Z)
    groups:
        - id
        - ignore
        - ignore
        - ignore
        - title
        - text # text must be specified if 'groups' exists
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - der Delegierten .+?\n