motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: (Satzung Nr\. \d+)\n\n(.+?)\n\n(.+?)\n\n(.+?)(?=\nANTRAG|\Z)
    groups:
        - id
        - author
        - title
        - text
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - .+?, Delegierter?