motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: ([A-Z]+-\d+-?[A-Z]*)\s*(.+?)\n\n(.+?)(?=\n\n[A-Z]+-\d+|\Z)
    groups:
        - id
        - title
        - text # text must be specified if 'groups' exists
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - Gremium:?(.+?)(?=[A-Za-z]+:) # it is possible to specify multiple regex for one key
                - Antragsteller\*in:\s+(.+?)\n # symbols that have special meaning in regex must be escaped (for example * which means zero or more in regex, but in this case it should match a literal asterisk)
                - weitere Antragsteller\*innen\n\n(.+?)\n\n
        # add more keys if needed