motion:
    # this is the regex for one whole motion. it can include capturing groups. 
    # if it does, specify the groups in 'groups' in the order they appear in the regex.
    regex: (([A-Z]{1,3})-([A-Z]*-?)?\d{2}(-\d{3})?(-\d)?)\s+?(.*?)\n\n(?:Antragsteller\*in:\s*(.*?))\n\n(.+?)\n\n(.+?)\n\n(.+?)(?=^[\x0c]?([A-Z]{2,3})-|[A-Z]-\d|\Z)
    groups:
        - id
        - ignore
        - ignore
        - ignore
        - ignore
        - topic
        - author
        - title
        - date
        - text
    keys: # keys are extracted either from 'text' if 'groups' is specified, otherwise from the motion captured by the above regex
        author: # these key names (e.g., author) can be freely chosen
            regex: 
                - Delegierten